version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    runtime: nvidia
    image: frigate:latest
    shm_size: "2gb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes the PCI coral
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/frigate/config.yml:/config/config.yml:ro
      - /media/surveillance/frigate:/media/frigate
      - /etc/frigate/db:/db
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
